### ISSUE TITLE
Bizzarre looking greyspace on the right side of table

### ISSUE THREAD

**Issue by anande** [gonzalovsilva/joplin-dark-theme#1]
Creating a table with less number of columns, creates this bizzare looking extra gray space on the right of the table:

Example Table: 
| <span style="color: #0b0b0b;">Place</span> | <span style="color: #0b0b0b;">State</span> | <span style="color: #0b0b0b;">Country</span> |
| --- | --- | --- |
| Hampi | KA  | IND |
| Jim Corb National Park |     | IND |
| HiraPanna-Pench National park |     | IND |
| Bandhavgarh National Park |     | IND |
|     | Assam | IND |
|     | Meghalay | IND |

Rendered markdown:
![Screenshot 2022-11-14 at 12 01 00 PM](https://user-images.githubusercontent.com/11643928/201590893-26b1ac7a-70e5-49af-8b11-027f0ff022ac.png)

That bizzarre grey space on the right looks like a merged row+column.
Can you fix this in the CSS maybe?

**Comment by gonzalovsilva** [comment]
![image](https://user-images.githubusercontent.com/77069600/202907181-4ff7e129-5fae-48c4-b7bf-c93eb7431c42.png)
This issue is now fixed. Hope that you still enjoy this theme.

**Comment by anande** [comment]
_Awesome! Thanks for the quick fix_ 👍 _Looks beautiful now_
