### ISSUE TITLE
Code block background

### ISSUE THREAD

**Issue by adam-ahern** [gonzalovsilva/joplin-dark-theme#2]
Hey Gonzalo,

I love your theme and it's made Joplin dark mode usable for me, so thank you. I am wondering if it's possible to have more of a contrast between the font colour of code and the code block background.

I've attached the screenshot of what it looks like. It's generally OK, but in bright rooms it's very hard to distinguish.

![Screenshot 2022-12-15 at 11 39 50](https://user-images.githubusercontent.com/26538900/207850422-c44d816f-7a0e-4fae-a2f4-97205bf4ae68.png)

Thank you & regards,
Adam

**Comment by gonzalovsilva** [comment]
Hi, thanks for your feedback, but basically I do it that way so the actual
code is more contrasty than the comments. It's the same thing for images
links for example. So the meta info is not obvious at the first glance and
don't remove the focus on the content that you're trying to review.

Hope that helps to understand a bit the "why" behind that decision. But I
guess that I could create a new variant for people that want to have that
kind of info more readable.

Le jeu. 15 déc. 2022 à 12:41, Adam Ahern ***@***.***> a
écrit :

**Comment by adam-ahern** [comment]
Hey @gonzalovsilva, thanks for your response. I appreciate you taking the time to describe this to me. Totally understand the decision here!
