### ISSUE TITLE
Selected note is not highlighted

### ISSUE THREAD

**Issue by electricar** [gonzalovsilva/joplin-dark-theme#3]
Hello,

thank you for this great theme. It is my favorite one!
Unfortunatly, since a few Joplin versions the selected note is not highlighted anymore.
Do you know what is the issue?
Thank you very much in advance!

![joplin](https://github.com/gonzalovsilva/joplin-dark-theme/assets/16311580/16dbee69-6780-460a-ace8-3b3e654464a4)

**Comment by gonzalovsilva** [comment]
Hi, thank you for letting me know about this. I'll have a look at it during next weekend.

**Comment by electricar** [comment]
> Hi, thank you for letting me know about this. I'll have a look at it during next weekend.

Ok great. This theme has the fix already, but I don't know how to change the colors to my liking:
https://github.com/catppuccin/joplin

I copied the color codes into my old userchrome.css, and copied this part from the catppuccin theme, while commeting your part:

![joplin2](https://github.com/gonzalovsilva/joplin-dark-theme/assets/16311580/ecbce7b4-267c-4f2f-be2d-455f241a82e5)

![joplin1](https://github.com/gonzalovsilva/joplin-dark-theme/assets/16311580/944819e9-4cf6-4606-a177-e2db46f36b95)

**Comment by gonzalovsilva** [comment]
Fixed.
